name: CI

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Format Check
        run: cargo fmt --all -- --check
